import hashlib, secrets, re
from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select, func, delete
from sqlalchemy.orm import Session
from backend.api.deps import current_user
from backend.core.db import get_db
from backend.core.security import create_token, hash_password, verify_password
from backend.core.config import settings
from backend.models import User, PhoneVerification
from backend.schemas.auth import RegisterIn, LoginIn, TokenOut, PhoneRequestIn, PhoneVerifyIn, CompleteProfileIn

router = APIRouter(prefix='/auth', tags=['auth'])

PHONE_RE = re.compile(r'^\+[1-9]\d{6,14}$')

def clean_username(value: str) -> str:
    return value.strip().lower()

def normalize_phone(value: str) -> str:
    value = value.strip().replace(' ', '').replace('-', '').replace('(', '').replace(')', '')
    if value.startswith('00'):
        value = '+' + value[2:]
    if not PHONE_RE.fullmatch(value):
        raise HTTPException(422, 'Введите номер в международном формате, например +491701234567')
    return value

def code_hash(code: str) -> str:
    return hashlib.sha256((settings.otp_pepper + ':' + code).encode()).hexdigest()

async def send_sms(phone: str, code: str) -> None:
    # Real SMS delivery: Twilio Verify. The code is generated by Twilio in production.
    if settings.twilio_account_sid and settings.twilio_auth_token and settings.twilio_verify_service_sid:
        import httpx
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                f'https://verify.twilio.com/v2/Services/{settings.twilio_verify_service_sid}/Verifications',
                data={'To': phone, 'Channel': 'sms'},
                auth=(settings.twilio_account_sid, settings.twilio_auth_token),
            )
        if r.status_code >= 400:
            raise HTTPException(502, 'Не удалось отправить SMS-код. Проверьте номер и настройки SMS-провайдера.')
        return
    # Local/demo mode: keep a server-side code so the flow remains testable.
    # Never expose it in the API response.

def check_twilio_enabled() -> bool:
    return bool(settings.twilio_account_sid and settings.twilio_auth_token and settings.twilio_verify_service_sid)

@router.post('/phone/request')
async def phone_request(data: PhoneRequestIn, db: Session = Depends(get_db)):
    phone = normalize_phone(data.phone)
    existing = db.scalar(select(User).where(User.phone == phone))
    if data.purpose == 'register' and existing:
        raise HTTPException(409, 'Этот номер уже зарегистрирован. Выберите вход.')
    if data.purpose == 'login' and not existing:
        raise HTTPException(404, 'Аккаунт с таким номером не найден. Сначала зарегистрируйтесь.')

    now = datetime.now(timezone.utc)
    recent = db.scalar(select(PhoneVerification).where(
        PhoneVerification.phone == phone,
        PhoneVerification.purpose == data.purpose,
        PhoneVerification.used == False,
        PhoneVerification.created_at > now - timedelta(seconds=45),
    ).order_by(PhoneVerification.id.desc()))
    if recent:
        raise HTTPException(429, 'Новый код можно запросить через несколько секунд.')

    code = f'{secrets.randbelow(1_000_000):06d}'
    db.add(PhoneVerification(phone=phone, purpose=data.purpose, code_hash=code_hash(code), expires_at=now + timedelta(minutes=5)))
    db.commit()
    if check_twilio_enabled():
        # We use Twilio Verify's generated code, so the local code is only a placeholder.
        await send_sms(phone, code)
    else:
        # Dev mode intentionally logs the OTP instead of returning it to the browser.
        print(f'[FENIX OTP DEV] {data.purpose} {phone}: {code}', flush=True)
    return {'ok': True, 'phone': phone, 'expires_in': 300, 'delivery': 'sms' if check_twilio_enabled() else 'development_log'}

@router.post('/phone/verify')
async def phone_verify(data: PhoneVerifyIn, db: Session = Depends(get_db)):
    phone = normalize_phone(data.phone)
    now = datetime.now(timezone.utc)
    record = db.scalar(select(PhoneVerification).where(
        PhoneVerification.phone == phone,
        PhoneVerification.purpose == data.purpose,
        PhoneVerification.used == False,
    ).order_by(PhoneVerification.id.desc()))
    if not record or record.expires_at.replace(tzinfo=timezone.utc) < now:
        raise HTTPException(400, 'Код истёк. Запросите новый код.')
    if record.attempts >= 5:
        raise HTTPException(429, 'Слишком много попыток. Запросите новый код.')

    if check_twilio_enabled():
        import httpx
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                f'https://verify.twilio.com/v2/Services/{settings.twilio_verify_service_sid}/VerificationCheck',
                data={'To': phone, 'Code': data.code.strip()},
                auth=(settings.twilio_account_sid, settings.twilio_auth_token),
            )
        if r.status_code >= 400 or r.json().get('status') != 'approved':
            record.attempts += 1; db.commit()
            raise HTTPException(400, 'Неверный код подтверждения.')
    elif not secrets.compare_digest(record.code_hash, code_hash(data.code.strip())):
        record.attempts += 1; db.commit()
        raise HTTPException(400, 'Неверный код подтверждения.')

    record.used = True
    db.commit()
    user = db.scalar(select(User).where(User.phone == phone))
    if data.purpose == 'login':
        if not user:
            raise HTTPException(404, 'Аккаунт не найден.')
        user.online = True; db.commit()
        return {'status': 'authenticated', **TokenOut(access_token=create_token(user.id)).model_dump()}
    # short-lived signed token is represented by a normal JWT with a dedicated purpose claim.
    from jose import jwt
    now_ts = int(now.timestamp())
    payload = {'sub': phone, 'typ': 'phone_signup', 'iat': now_ts, 'exp': now_ts + 15 * 60}
    signup_token = jwt.encode(payload, settings.jwt_secret, algorithm=settings.jwt_algorithm)
    return {'status': 'verified', 'signup_token': signup_token, 'phone': phone}

@router.post('/phone/complete', response_model=TokenOut)
def phone_complete(data: CompleteProfileIn, signup_token: str, db: Session = Depends(get_db)):
    from jose import jwt, JWTError
    try:
        payload = jwt.decode(signup_token, settings.jwt_secret, algorithms=[settings.jwt_algorithm])
        if payload.get('typ') != 'phone_signup': raise ValueError()
        phone = normalize_phone(str(payload['sub']))
    except Exception:
        raise HTTPException(401, 'Сессия регистрации истекла. Запросите SMS-код заново.')
    username = clean_username(data.username)
    if len(username) < 5: raise HTTPException(422, 'Юзернейм должен содержать минимум 5 символов')
    if db.scalar(select(User).where(User.username == username)):
        raise HTTPException(409, 'Этот юзернейм уже занят')
    if db.scalar(select(User).where(User.phone == phone)):
        raise HTTPException(409, 'Этот номер уже зарегистрирован')
    is_first = db.scalar(select(func.count(User.id))) == 0
    # Phone-first accounts don't require a password; keep a random hash for legacy schema compatibility.
    user = User(
        username=username,
        display_name=data.display_name.strip(),
        password_hash=hash_password(secrets.token_urlsafe(32)),
        phone=phone,
        avatar=data.avatar,
        online=True,
        role='owner' if is_first else 'user',
    )
    db.add(user); db.commit(); db.refresh(user)
    return TokenOut(access_token=create_token(user.id))

@router.post('/register', response_model=TokenOut, status_code=201)
def register(data: RegisterIn, db: Session = Depends(get_db)):
    username = clean_username(data.username)
    if len(username) < 5:
        raise HTTPException(422, 'Юзернейм должен содержать минимум 5 символов')
    if db.scalar(select(User).where(User.username == username)):
        raise HTTPException(409, 'Пользователь с таким юзернеймом уже существует')
    is_first = db.scalar(select(func.count(User.id))) == 0
    user = User(username=username, display_name=data.display_name.strip(), password_hash=hash_password(data.password), online=True, role='owner' if is_first else 'user')
    db.add(user); db.commit(); db.refresh(user)
    return TokenOut(access_token=create_token(user.id))

@router.post('/login', response_model=TokenOut)
def login(data: LoginIn, db: Session = Depends(get_db)):
    username = clean_username(data.username)
    user = db.scalar(select(User).where(User.username == username))
    if user is None or not verify_password(data.password, user.password_hash):
        raise HTTPException(401, 'Неверный юзернейм или пароль')
    user.online = True; db.commit()
    return TokenOut(access_token=create_token(user.id))

@router.get('/me')
def auth_me(u=Depends(current_user)):
    return u

@router.post('/logout')
def logout(u=Depends(current_user), db: Session = Depends(get_db)):
    u.online = False; db.commit(); return {'ok': True}
