from pathlib import Path
p=Path('/mnt/data/fenix_tz/frontend/dist/assets/app.js')
s=p.read_text()
old=s[s.index('function renderApp()'):s.index('function openChat')]
new=r'''function renderApp(){document.body.dataset.theme=state.theme;document.body.innerHTML=`<div class="app ${state.chat?'mobile-chat':''}">
<aside class="sidebar">
<div class="side-top"><button class="icon-btn" id="menu">☰</button><div class="search"><span>⌕</span><input id="global-search" placeholder="Поиск" value="${esc(state.search)}"></div><button class="icon-btn desktop-only" id="top-more">⋮</button></div>
<div class="stories"><button class="story add"><span class="story-avatar">＋</span><small>Моя история</small></button>${state.chats.slice(0,7).map(c=>`<button class="story"><span class="story-avatar">${avatar(c,'story-img')}</span><small>${esc((c.title||'История').slice(0,10))}</small></button>`).join('')}</div>
<div class="folders"><button class="folder ${state.section==='chats'?'active':''}" data-section="chats">Все чаты</button><button class="folder ${state.section==='unread'?'active':''}" data-section="unread">Непрочитанные</button><button class="folder ${state.section==='groups'?'active':''}" data-section="groups">Группы</button><button class="folder ${state.section==='channels'?'active':''}" data-section="channels">Каналы</button><button class="folder ${state.section==='saved'?'active':''}" data-section="saved">Избранное</button><button class="folder add-folder" id="add-folder">＋</button></div>
<div class="archive-row" id="archive"><span>▣</span><div><b>Архив</b><small>Скрытые чаты</small></div><span class="archive-count">${state.chats.filter(c=>c.archived).length||''}</span></div>
<div id="chat-list" class="chat-list"></div>
<div class="profile-mini" id="profile-open">${avatar(state.me)}<div><b>${esc(state.me?.display_name)}</b><small>@${esc(state.me?.username)}</small></div><button class="dots">⋮</button></div>
</aside>
<main class="chat-area"><div id="chat-content"></div></main>
<nav class="mobile-nav"><button class="${!state.chat&&state.section==='chats'?'active':''}" data-nav="chats">💬<span>Чаты</span></button><button data-nav="contacts">👥<span>Контакты</span></button><button data-nav="settings">⚙️<span>Настройки</span></button><button data-nav="profile">👤<span>Профиль</span></button></nav>
<button class="fab" id="compose-fab" aria-label="Создать">✎</button><div id="drawer"></div></div>`;bindApp();renderChatList();renderChat()}
function bindApp(){$('#menu').onclick=()=>openDrawer('menu');$('#profile-open').onclick=()=>openDrawer('profile');$('#top-more')?.addEventListener('click',()=>openDrawer('menu'));$('#compose-fab')?.addEventListener('click',()=>openDrawer('compose'));$('#add-folder')?.addEventListener('click',()=>toast('Создание папок будет доступно в следующем обновлении'));$('#archive')?.addEventListener('click',()=>toast('Архив готовится'));$('#global-search').oninput=e=>{state.search=e.target.value;renderChatList()};$$('.folder').forEach(b=>b.onclick=()=>{state.section=b.dataset.section;$$('.folder').forEach(x=>x.classList.toggle('active',x===b));renderChatList()});$$('.mobile-nav button').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='chats'){state.chat=null;state.section='chats';renderApp()}else if(n==='profile')openDrawer('profile');else openDrawer(n==='settings'?'settings':'contacts')})}
function filteredChats(){let a=[...state.chats];if(state.section==='groups')a=a.filter(x=>x.kind==='group');if(state.section==='channels')a=a.filter(x=>x.kind==='channel');if(state.section==='saved')a=a.filter(x=>x.kind==='saved');if(state.section==='unread')a=a.filter(x=>(x.unread_count||x.unread||0)>0);if(state.search){const q=state.search.toLowerCase();a=a.filter(x=>(x.title||'').toLowerCase().includes(q)||(x.username||'').toLowerCase().includes(q))}return a.filter(x=>!x.archived)}
function renderChatList(){const el=$('#chat-list');if(!el)return;const a=filteredChats();el.innerHTML=a.length?a.map(c=>{const unread=Number(c.unread_count||c.unread||0);const muted=c.muted||c.notifications===false;const last=c.last_message||c.preview||'';return `<button class="chat-row ${state.chat?.id===c.id?'selected':''}" data-id="${c.id}">${avatar(c)}<span class="chat-meta"><span class="chat-line"><b>${esc(c.title)}</b><time>${esc(c.last_time||c.updated_at?new Date(c.last_time||c.updated_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'')}</time></span><small class="chat-preview">${c.pinned?'📌 ':''}${muted?'🔕 ':''}${esc(last|| (c.kind==='channel'?'Канал':c.kind==='group'?'Группа':'Нет сообщений'))}</small><span class="chat-bottom"><small>${c.kind==='channel'?'Канал':c.kind==='group'?'Группа':c.kind==='saved'?'Избранное':''}</small>${unread?`<em>${unread>99?'99+':unread}</em>`:''}</span></span></button>`}).join(''):`<div class="empty-list"><div>⌕</div><b>Чатов пока нет</b><small>Найдите человека через «Контакты» или создайте новый чат.</small></div>`;$$('.chat-row').forEach(x=>x.onclick=()=>openChat(Number(x.dataset.id)))}
'''
s=s.replace(old,new)
# Enhance chat renderer and message html
start=s.index('function renderChat()'); end=s.index('function bindChat()', start)
old2=s[start:end]
new2=r'''function renderChat(){const el=$('#chat-content');if(!el)return;if(!state.chat){el.innerHTML=`<div class="empty-chat"><div class="empty-logo">✈</div><h2>Fenix Messenger</h2><p>Выберите чат слева или найдите пользователя в контактах.</p><button class="primary" id="empty-contacts">Найти людей</button></div>`;$('#empty-contacts')?.addEventListener('click',()=>{openDrawer('contacts');setTimeout(bindPeople,50)});return}el.innerHTML=`<header class="chat-header"><button class="mobile-back icon-btn" id="back-chats">‹</button><button class="chat-head-main" id="chat-profile">${avatar(state.chat)}<div><b>${esc(state.chat.title)}</b><small>${state.chat.typing?'печатает...':state.chat.kind==='channel'?'канал':state.chat.kind==='group'?`${state.chat.members_count||0} участников`:'в сети'}</small></div></button><div class="chat-head-actions"><button class="icon-btn" id="call-audio">☎</button><button class="icon-btn" id="call-video">▣</button><button class="icon-btn" id="chat-more">⋮</button></div></header><div class="pinned"><span>📌</span><div><b>Закреплённые сообщения</b><small>Нажмите, чтобы открыть</small></div><b>›</b></div><div class="messages" id="messages">${state.messages.map(messageHTML).join('')}</div><div class="composer-wrap">${state.reply?`<div class="reply-bar"><b>Ответ</b><span>${esc(state.reply.text||'Медиа')}</span><button id="cancel-reply">×</button></div>`:''}<div class="composer"><button class="icon-btn" id="attach">＋</button><textarea id="message-input" rows="1" placeholder="Сообщение">${esc(state.editing?.text||'')}</textarea><button class="icon-btn" id="emoji">☺</button><button class="send-btn" id="send">${state.editing?'✓':'➤'}</button></div></div>`;bindChat();$('#back-chats')?.addEventListener('click',()=>{state.chat=null;renderApp()});$('#chat-profile')?.addEventListener('click',()=>openDrawer('profile'));scrollBottom()}
function messageHTML(m){const mine=m.sender_id===state.me?.id;const time=new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});const reaction=m.reaction||m.reactions?.[0]?.emoji;return `<div class="message ${mine?'mine':''} ${m.deleted?'deleted':''}" data-id="${m.id}"><div class="bubble"><div class="message-author">${mine?'Вы':esc(m.sender_name||'Fenix user')}</div>${m.reply_to_text?`<div class="reply-ref">${esc(m.reply_to_text)}</div>`:''}<div class="message-text">${m.deleted?'<i>Сообщение удалено</i>':esc(m.text||'')}</div>${m.media_url?`<div class="media-card">📎 <span>${esc(m.media_type||'Вложение')}</span></div>`:''}<div class="message-meta"><span>${m.edited?'изменено · ':''}${time}</span>${mine?'<span class="checks">✓✓</span>':''}</div>${reaction?`<button class="reaction-pill">${esc(reaction)} <small>1</small></button>`:''}<button class="message-menu">⋮</button></div></div>`}
'''
s=s.replace(old2,new2)
# add compose drawer
needle="function openDrawer(type,data){const d=$('#drawer');if(!d)return;let html='';if(type==='menu')"
replacement="function openDrawer(type,data){const d=$('#drawer');if(!d)return;let html='';if(type==='compose')html=`<div class=\"sheet compose-sheet\"><div class=\"sheet-title\">Создать</div><button class=\"sheet-item\" data-action=\"contacts\">💬 Новый чат</button><button class=\"sheet-item\" data-action=\"new-group\">👥 Новая группа</button><button class=\"sheet-item\" data-action=\"new-channel\">📣 Новый канал</button><button class=\"sheet-item\">🔐 Новый секретный чат</button><button class=\"sheet-item\">📁 Новая папка</button><button id=\"drawer-close\" class=\"sheet-cancel\">Отмена</button></div>`;if(type==='menu')"
s=s.replace(needle,replacement)
# add action no-op notices
needle2="if(a==='logout')"
s=s.replace(needle2,"if(a==='new-group'||a==='new-channel'){closeDrawer();toast(a==='new-group'?'Создание группы будет доступно в следующем обновлении':'Создание канала будет доступно в следующем обновлении');return}if(a==='logout')")
p.write_text(s)
